version: 2
jobs:
  build:
    docker:
      - image: cimg/node:12.16
    steps:
      - checkout

      - run:
          name: Install JavaScript dependencies
          command: |
            npm ci

      - run:
          name: Run linter
          command: |
            npm run lint

      - run:
          name: Build React app
          command: |
            npm run build

      - persist_to_workspace:
          root: .
          paths:
            - build/*

  deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout

      - restore_cache:
          key: v1-dependency-cache-{{ checksum "setup.py" }}
      
      - attach_workspace:
          at: .

      - run:
          name: Move React app to Tornado static directory
          command: |
            mv build mopidy_pibox/static

      - run:
          name: Install python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install twine
            pip install -e .
      - save_cache:
          key: v1-dependency-cache-{{ checksum "setup.py" }}
          paths:
            - "venv"

      - run:
          name: Init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = gbannerman" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: Create packages
          command: |
            python setup.py sdist
      - run:
          name: Upload to pypi
          command: |
            . venv/bin/activate
            twine upload dist/*

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master